version: '3'

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
  uwsgi:
    build:
      context: ./uwsgi/
      dockerfile: Dockerfile
    restart: always
